name: Compatibility with pynxtools

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pynx_compatibility:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # TODO check Disable this test from block merge request
      matrix:
        pynxtools_versions: ["latest", "v0.9.3"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install uv and set the python version to $3.12
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
      - name: Install pynxtools-xps
        run: |
          uv pip install ".[dev]"
          uv pip install coverage coveralls
      - name: Install pynxtools release version ${{ matrix.pynxtools_versions }}
        run: |
          if [ "${{ matrix.pynxtools_versions }}" == "latest" ]; then
            uv pip install pynxtools
          else
           uv pip install pynxtools==${{ matrix.pynxtools_versions }}
          fi
      - name: Run tests
        run: |
          pytest tests/.