jobs:
  update-version-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update version
        run: |
          sed -i "s/version: .*/version: ${{ github.event.inputs.version }}/g" CITATION.cff

      - name: Commit changes to a new branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b update-version-${{ github.event.inputs.version }}
          git commit -am "Update CITATION.cff version to ${{ github.event.inputs.version }}"
          git push origin update-version-${{ github.event.inputs.version }}

      - name: Create pull request
        uses: actions/github-script@v6
        with:
          script: |
            const version = github.inputs.version;
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Update CITATION.cff version to ${version}`,
              head: `update-version-${version}`,
              base: `main`,
              body: `This PR updates the CITATION.cff version to ${version}`
            })
