# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pynxtools-xps
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv and use the python version 3.12
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12
      
      # Final pytest with pynxtools before release
      - name: Install pynxtools-xps
        run: |
          uv pip install ".[dev]"
          uv pip install coverage coveralls
      - name: Install latest pynxtools release
        run: |
          uv pip install pynxtools
      
      - name: Run tests
        run: |
          pytest tests/.

      # Build
      - name: Install builddependencies
        run: |
          uv pip install build
      - name: Build package
        run: python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
